services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rdb:
    image: redis:latest
    container_name: rdb
    restart: unless-stopped
    ports:
      - ${RDB_PORT}:${RDB_PORT}
    volumes:
      - rdb_data:/var/lib/redis/data
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/hona-tahlil/backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - db
      - rdb
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - web

volumes:
  pgdata:
  rdb_data:

networks:
  web:
    external: true
