services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web

  rdb:
    image: redis:latest
    container_name: rdb
    restart: unless-stopped
    ports:
      - ${RDB_PORT}:${RDB_PORT}
    volumes:
      - rdb_data:/var/lib/redis/data
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
    networks:
      - web

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/hona-tahlil/backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - db
      - rdb
      - rabbitmq
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    expose:
      - "8080"
    networks:
      - web

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "${AMQP_PORT}:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USER}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${AMQP_VHOST}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - web

volumes:
  pgdata:
  rdb_data:
  rabbitmq_data:

networks:
  web:
    external: true
