// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"hona/backend/bootstrap"
	"hona/backend/internal/application/service"
	"hona/backend/internal/application/usecase"
	"hona/backend/internal/domain/jwt"
	"hona/backend/internal/domain/ports"
<<<<<<< HEAD
=======
	"hona/backend/internal/domain/ports/redis"
>>>>>>> dev
	"hona/backend/internal/domain/storage"
	"hona/backend/internal/infrastructure/jwt"
	"hona/backend/internal/infrastructure/mail"
	"hona/backend/internal/infrastructure/persistence"
<<<<<<< HEAD
	"hona/backend/internal/infrastructure/persistence/seeder"
	"hona/backend/internal/infrastructure/storage"
	"hona/backend/internal/presentation/controllers/v1/admin"
	"hona/backend/internal/presentation/controllers/v1/general"
	"hona/backend/internal/presentation/controllers/v1/petsitter"
=======
	"hona/backend/internal/infrastructure/persistence/repository/redis"
	"hona/backend/internal/infrastructure/seeder"
	"hona/backend/internal/infrastructure/storage"
	"hona/backend/internal/presentation/controllers/v1/admin"
	"hona/backend/internal/presentation/controllers/v1/general"
	"hona/backend/internal/presentation/controllers/v1/pet_sitter"
	"hona/backend/internal/presentation/controllers/v1/user"
>>>>>>> dev
	"hona/backend/internal/presentation/middleware"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Config) (*Application, error) {
	jwtKeyManager := jwt.NewJWTKeyManager()
	jwtService := jwt.NewJWTService(jwtKeyManager)
	db := persistence.NewPostgresDatabase()
	unitOfWork := persistence.NewUnitOfWork(db)
	redisDatabase := persistence.NewRedisDatabase()
	userCacheRepository := redis.NewUserCacheRepository(redisDatabase)
	emailService := mail.NewEmailService()
	userService := service.NewUserService(jwtService, unitOfWork, userCacheRepository, emailService)
	generalUserController := general.NewGeneralUserController(userService)
	s3Storage := storage.NewS3Storage()
	petService := service.NewPetService(unitOfWork, s3Storage, userService)
	generalPetController := general.NewGeneralPetController(petService)
	provinceService := service.NewProvinceService(unitOfWork)
	generalProvinceController := general.NewGeneralProvinceController(provinceService)
	generalControllers := &GeneralControllers{
		GeneralUserController:     generalUserController,
		GeneralPetController:      generalPetController,
		GeneralProvinceController: generalProvinceController,
	}
	rbacService := service.NewRBACService(unitOfWork, userService)
	adminRBACController := admin.NewAdminRBACController(rbacService)
	adminControllers := &AdminControllers{
		AdminRBACController: adminRBACController,
	}
<<<<<<< HEAD
	s3Storage := storage.NewS3Storage()
	provinceService := service.NewProvinceService(unitOfWork)
	addressService := service.NewAddressService(unitOfWork, provinceService)
	petSitterService := service.NewPetSitterService(unitOfWork, s3Storage, userService, addressService)
	petSitterController := petsitter.NewPetsitterController(petSitterService)
	wirePetSitterController := &PetSitterController{
		PetSitterController: petSitterController,
	}
	controllers := &Controllers{
		GeneralControllers:  generalControllers,
		AdminControllers:    adminControllers,
		PetSitterController: wirePetSitterController,
=======
	userPetController := user.NewUserPetController(petService)
	addressService := service.NewAddressService(unitOfWork, provinceService, userService)
	serviceService := service.NewServiceService(unitOfWork)
	calendarSlotService := service.NewCalendarSlotService()
	petSitterService := service.NewPetSitterService(unitOfWork, userService, serviceService, calendarSlotService)
	requestServiceDeps := service.RequestServiceDeps{
		UserService:         userService,
		ProvinceService:     provinceService,
		AddressService:      addressService,
		PetService:          petService,
		ServiceService:      serviceService,
		PetSitterService:    petSitterService,
		CalendarSlotService: calendarSlotService,
		UnitOfWork:          unitOfWork,
		EmailService:        emailService,
	}
	requestService := service.NewRequestService(requestServiceDeps)
	userRequestController := user.NewUserRequestController(requestService)
	userControllers := &UserControllers{
		UserPetController:     userPetController,
		UserRequestController: userRequestController,
	}
	petSitterControllers := &PetSitterControllers{}
	controllers := &Controllers{
		GeneralControllers:   generalControllers,
		AdminControllers:     adminControllers,
		UserControllers:      userControllers,
		PetSitterControllers: petSitterControllers,
>>>>>>> dev
	}
	localizationMiddleware := middleware.NewLocalizationMiddleware()
	recoveryMiddleware := middleware.NewRecoveryMiddleware()
	authMiddleware := middleware.NewAuthMiddleware(jwtService)
<<<<<<< HEAD
=======
	rbacMiddleware := middleware.NewRBACMiddleware(unitOfWork)
>>>>>>> dev
	corsMiddleware := middleware.NewCORSMiddleware()
	middlewares := &Middlewares{
		LocalizationMiddleware: localizationMiddleware,
		RecoveryMiddleware:     recoveryMiddleware,
		AuthMiddleware:         authMiddleware,
<<<<<<< HEAD
=======
		RBACMiddleware:         rbacMiddleware,
>>>>>>> dev
		CORSMiddleware:         corsMiddleware,
	}
	databaseSeeder := seeder.NewDatabaseSeeder(db)
	wireSeeder := &Seeder{
		DatabaseSeeder: databaseSeeder,
	}
	wireStorage := &Storage{
		S3Storage: s3Storage,
	}
	application := NewApplication(controllers, middlewares, wireSeeder, wireStorage)
	return application, nil
}

// wire.go:

var StorageProviderSet = wire.NewSet(storage.NewS3Storage, wire.Bind(new(domainstorage.Storage), new(*storage.S3Storage)), wire.Struct(new(Storage), "*"))
<<<<<<< HEAD

var RepositoryProviderSet = wire.NewSet(persistence.NewRepositoryFactory, persistence.NewUnitOfWork, persistence.NewPostgresDatabase, wire.Bind(new(ports.RepositoryFactory), new(*persistence.RepositoryFactory)), wire.Bind(new(ports.UnitOfWork), new(*persistence.UnitOfWork)))

var ServiceProviderSet = wire.NewSet(service.NewUserService, jwt.NewJWTService, jwt.NewJWTKeyManager, service.NewRBACService, service.NewProvinceService, service.NewAddressService, service.NewPetSitterService, wire.Bind(new(domainjwt.JWTService), new(*jwt.JWTService)), wire.Bind(new(domainjwt.JWTKeyManager), new(*jwt.JWTKeyManager)), wire.Bind(new(usecase.RBACService), new(*service.RBACService)), wire.Bind(new(usecase.UserService), new(*service.UserService)), wire.Bind(new(usecase.ProvinceService), new(*service.ProvinceService)), wire.Bind(new(usecase.AddressService), new(*service.AddressService)), wire.Bind(new(usecase.PetSitterService), new(*service.PetSitterService)))
=======

var RepositoryProviderSet = wire.NewSet(persistence.NewRepositoryFactory, persistence.NewUnitOfWork, persistence.NewPostgresDatabase, persistence.NewRedisDatabase, redis.NewUserCacheRepository, wire.Bind(new(persistence.Cache), new(*persistence.RedisDatabase)), wire.Bind(new(domainredis.UserCacheRepository), new(*redis.UserCacheRepository)), wire.Bind(new(ports.RepositoryFactory), new(*persistence.RepositoryFactory)), wire.Bind(new(ports.UnitOfWork), new(*persistence.UnitOfWork)))
>>>>>>> dev

var ServiceProviderSet = wire.NewSet(wire.Struct(new(service.RequestServiceDeps), "*"), service.NewUserService, jwt.NewJWTService, jwt.NewJWTKeyManager, mail.NewEmailService, service.NewRBACService, service.NewPetService, service.NewRequestService, service.NewProvinceService, service.NewAddressService, service.NewCalendarSlotService, service.NewPetSitterService, service.NewServiceService, wire.Bind(new(domainjwt.JWTService), new(*jwt.JWTService)), wire.Bind(new(domainjwt.JWTKeyManager), new(*jwt.JWTKeyManager)), wire.Bind(new(usecase.RBACService), new(*service.RBACService)), wire.Bind(new(usecase.UserService), new(*service.UserService)), wire.Bind(new(usecase.PetService), new(*service.PetService)), wire.Bind(new(usecase.RequestService), new(*service.RequestService)), wire.Bind(new(usecase.ProvinceService), new(*service.ProvinceService)), wire.Bind(new(usecase.AddressService), new(*service.AddressService)), wire.Bind(new(usecase.CalendarSlotService), new(*service.CalendarSlotService)), wire.Bind(new(usecase.PetSitterService), new(*service.PetSitterService)), wire.Bind(new(usecase.ServiceService), new(*service.ServiceService)))

var GeneralControllersProviderSet = wire.NewSet(general.NewGeneralUserController, general.NewGeneralPetController, general.NewGeneralProvinceController, wire.Struct(new(GeneralControllers), "*"))

var AdminControllersProviderSet = wire.NewSet(admin.NewAdminRBACController, wire.Struct(new(AdminControllers), "*"))

<<<<<<< HEAD
var PetSitterControllersProviderSet = wire.NewSet(petsitter.NewPetsitterController, wire.Struct(new(PetSitterController), "*"))

var ControllersProviderSet = wire.NewSet(wire.Struct(new(Controllers), "*"))

var MiddlewaresProviderSet = wire.NewSet(middleware.NewLocalizationMiddleware, middleware.NewRecoveryMiddleware, middleware.NewAuthMiddleware, middleware.NewCORSMiddleware, wire.Struct(new(Middlewares), "*"))
=======
var UserControllersProviderSet = wire.NewSet(user.NewUserPetController, user.NewUserRequestController, wire.Struct(new(UserControllers), "*"))

var PetSitterControllersProviderSet = wire.NewSet(petsitter.NewPetSitterRequestController, wire.Struct(new(PetSitterControllers)))

var ControllersProviderSet = wire.NewSet(wire.Struct(new(Controllers), "*"))

var MiddlewaresProviderSet = wire.NewSet(middleware.NewLocalizationMiddleware, middleware.NewRecoveryMiddleware, middleware.NewRBACMiddleware, middleware.NewAuthMiddleware, middleware.NewCORSMiddleware, wire.Struct(new(Middlewares), "*"))
>>>>>>> dev

var SeederProviderSet = wire.NewSet(seeder.NewDatabaseSeeder, wire.Struct(new(Seeder), "*"))

var ProviderSet = wire.NewSet(
	MiddlewaresProviderSet,
	ControllersProviderSet,
	GeneralControllersProviderSet,
	AdminControllersProviderSet,
	UserControllersProviderSet,
	PetSitterControllersProviderSet,
	ServiceProviderSet,
	RepositoryProviderSet,
	SeederProviderSet,
	StorageProviderSet,
<<<<<<< HEAD
	PetSitterControllersProviderSet,
=======
>>>>>>> dev
)

type GeneralControllers struct {
	GeneralUserController     *general.GeneralUserController
	GeneralPetController      *general.GeneralPetController
	GeneralProvinceController *general.GeneralProvinceController
}

type AdminControllers struct {
	AdminRBACController *admin.AdminRBACController
}

<<<<<<< HEAD
type PetSitterController struct {
	PetSitterController *petsitter.PetSitterController
}

type Controllers struct {
	GeneralControllers  *GeneralControllers
	AdminControllers    *AdminControllers
	PetSitterController *PetSitterController
=======
type UserControllers struct {
	UserPetController     *user.UserPetController
	UserRequestController *user.UserRequestController
}

type PetSitterControllers struct {
	PetSitterRequestController *petsitter.PetSitterRequestController
}

type Controllers struct {
	GeneralControllers   *GeneralControllers
	AdminControllers     *AdminControllers
	UserControllers      *UserControllers
	PetSitterControllers *PetSitterControllers
>>>>>>> dev
}

type Middlewares struct {
	LocalizationMiddleware *middleware.LocalizationMiddleware
	RecoveryMiddleware     *middleware.RecoveryMiddleware
	AuthMiddleware         *middleware.AuthMiddleware
<<<<<<< HEAD
=======
	RBACMiddleware         *middleware.RBACMiddleware
>>>>>>> dev
	CORSMiddleware         *middleware.CORSMiddleware
}

type Seeder struct {
	DatabaseSeeder *seeder.DatabaseSeeder
}

type Storage struct {
	S3Storage *storage.S3Storage
}

type Application struct {
	Controllers *Controllers
	Middlewares *Middlewares
	Seeder      *Seeder
	Storage     *Storage
}

func NewApplication(controllers *Controllers, middlewares *Middlewares, seeder2 *Seeder, storage2 *Storage) *Application {
	return &Application{
		Controllers: controllers,
		Middlewares: middlewares,
		Seeder:      seeder2,
		Storage:     storage2,
	}
}
