// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"hona/backend/bootstrap"
	"hona/backend/internal/application/service"
	"hona/backend/internal/application/usecase"
	"hona/backend/internal/domain/jwt"
	"hona/backend/internal/domain/ports"
	"hona/backend/internal/infrastructure/jwt"
	"hona/backend/internal/infrastructure/persistence"
	"hona/backend/internal/infrastructure/persistence/seeder"
	"hona/backend/internal/presentation/controllers/v1/admin"
	"hona/backend/internal/presentation/controllers/v1/general"
	"hona/backend/internal/presentation/controllers/v1/petsitter"
	"hona/backend/internal/presentation/middleware"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Config) (*Application, error) {
	db := persistence.NewPostgresDatabase()
	unitOfWork := persistence.NewUnitOfWork(db)
	jwtKeyManager := jwt.NewJWTKeyManager()
	jwtService := jwt.NewJWTService(jwtKeyManager)
	userService := service.NewUserService(unitOfWork, jwtService)
	generalUserController := general.NewGeneralUserController(userService)
	generalControllers := &GeneralControllers{
		GeneralUserController: generalUserController,
	}
	rbacService := service.NewRBACService(unitOfWork, userService)
	adminRBACController := admin.NewAdminRBACController(rbacService)
	adminControllers := &AdminControllers{
		AdminRBACController: adminRBACController,
	}
	petSitterService := service.NewPetSitterService(unitOfWork)
	petSitterController := petsitter.NewPetsitterController(petSitterService)
	wirePetSitterController := &PetSitterController{
		PetSitterController: petSitterController,
	}
	controllers := &Controllers{
		GeneralControllers:  generalControllers,
		AdminControllers:    adminControllers,
		PetSitterController: wirePetSitterController,
	}
	localizationMiddleware := middleware.NewLocalizationMiddleware()
	recoveryMiddleware := middleware.NewRecoveryMiddleware()
	middlewares := &Middlewares{
		LocalizationMiddleware: localizationMiddleware,
		RecoveryMiddleware:     recoveryMiddleware,
	}
	databaseSeeder := seeder.NewDatabaseSeeder(db)
	wireSeeder := &Seeder{
		DatabaseSeeder: databaseSeeder,
	}
	application := NewApplication(controllers, middlewares, wireSeeder)
	return application, nil
}

// wire.go:

var RepositoryProviderSet = wire.NewSet(persistence.NewRepositoryFactory, persistence.NewUnitOfWork, persistence.NewPostgresDatabase, wire.Bind(new(ports.RepositoryFactory), new(*persistence.RepositoryFactory)), wire.Bind(new(ports.UnitOfWork), new(*persistence.UnitOfWork)))

var ServiceProviderSet = wire.NewSet(service.NewUserService, jwt.NewJWTService, jwt.NewJWTKeyManager, service.NewRBACService, service.NewPetSitterService, wire.Bind(new(domainjwt.JWTService), new(*jwt.JWTService)), wire.Bind(new(domainjwt.JWTKeyManager), new(*jwt.JWTKeyManager)), wire.Bind(new(usecase.RBACService), new(*service.RBACService)), wire.Bind(new(usecase.UserService), new(*service.UserService)), wire.Bind(new(usecase.PetSitterService), new(*service.PetSitterService)))

var GeneralControllersProviderSet = wire.NewSet(general.NewGeneralUserController, wire.Struct(new(GeneralControllers), "*"))

var AdminControllersProviderSet = wire.NewSet(admin.NewAdminRBACController, wire.Struct(new(AdminControllers), "*"))

var PetSitterControllersProviderSet = wire.NewSet(petsitter.NewPetsitterController, wire.Struct(new(PetSitterController), "*"))

var ControllersProviderSet = wire.NewSet(wire.Struct(new(Controllers), "*"))

var MiddlewaresProviderSet = wire.NewSet(middleware.NewLocalizationMiddleware, middleware.NewRecoveryMiddleware, wire.Struct(new(Middlewares), "*"))

var SeederProviderSet = wire.NewSet(seeder.NewDatabaseSeeder, wire.Struct(new(Seeder), "*"))

var ProviderSet = wire.NewSet(
	MiddlewaresProviderSet,
	ControllersProviderSet,
	GeneralControllersProviderSet,
	AdminControllersProviderSet,
	ServiceProviderSet,
	RepositoryProviderSet,
	SeederProviderSet,
	PetSitterControllersProviderSet,
)

type GeneralControllers struct {
	GeneralUserController *general.GeneralUserController
}

type AdminControllers struct {
	AdminRBACController *admin.AdminRBACController
}

type PetSitterController struct {
	PetSitterController *petsitter.PetSitterController
}

type Controllers struct {
	GeneralControllers  *GeneralControllers
	AdminControllers    *AdminControllers
	PetSitterController *PetSitterController
}

type Middlewares struct {
	LocalizationMiddleware *middleware.LocalizationMiddleware
	RecoveryMiddleware     *middleware.RecoveryMiddleware
}

type Seeder struct {
	DatabaseSeeder *seeder.DatabaseSeeder
}

type Application struct {
	Controllers *Controllers
	Middlewares *Middlewares
	Seeder      *Seeder
}

func NewApplication(controllers *Controllers, middlewares *Middlewares, seeder2 *Seeder) *Application {
	return &Application{
		Controllers: controllers,
		Middlewares: middlewares,
		Seeder:      seeder2,
	}
}
