// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"hona/backend/bootstrap"
	"hona/backend/internal/application/service"
	"hona/backend/internal/application/usecase"
	domainmail "hona/backend/internal/domain/mail"
	"hona/backend/internal/domain/ports"
	domainredis "hona/backend/internal/domain/ports/redis"
	domainstorage "hona/backend/internal/domain/storage"
	"hona/backend/internal/infrastructure/communication/mail"
	"hona/backend/internal/infrastructure/jwt"
	"hona/backend/internal/infrastructure/persistence"
	"hona/backend/internal/infrastructure/persistence/repository/redis"
	"hona/backend/internal/infrastructure/seeder"
	"hona/backend/internal/infrastructure/storage"
	"hona/backend/internal/infrastructure/websocket"
	"hona/backend/internal/presentation/controllers/v1/admin"
	"hona/backend/internal/presentation/controllers/v1/general"
	petsitter "hona/backend/internal/presentation/controllers/v1/pet_sitter"
	"hona/backend/internal/presentation/controllers/v1/user"
	"hona/backend/internal/presentation/middleware"

	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Config, hub *websocket.Hub) (*Application, error) {
	jwtKeyManager := jwt.NewJWTKeyManager()
	jwtService := jwt.NewJWTService(jwtKeyManager)
	db := persistence.NewPostgresDatabase()
	unitOfWork := persistence.NewUnitOfWork(db)
	redisDatabase := persistence.NewRedisDatabase()
	userCacheRepository := redis.NewUserCacheRepository(redisDatabase)
	emailService := mail.NewEmailService()
	addressService := service.NewAddressService(unitOfWork)
	s3Storage := storage.NewS3Storage()
	userService := service.NewUserService(jwtService, unitOfWork, userCacheRepository, emailService, addressService, s3Storage)
	generalUserController := general.NewGeneralUserController(userService)
	chatService := service.NewChatService(unitOfWork, userService)
	petService := service.NewPetService(unitOfWork, s3Storage, userService)
	generalPetController := general.NewGeneralPetController(petService)
	generalProvinceController := general.NewGeneralProvinceController(addressService)
	petSitterService := service.NewPetSitterService(unitOfWork, s3Storage, userService, addressService)
	generalSearchController := general.NewGeneralSearchController(petSitterService)
	generalControllers := &GeneralControllers{
		GeneralUserController:     generalUserController,
		GeneralPetController:      generalPetController,
		GeneralProvinceController: generalProvinceController,
		GeneralSearchController:   generalSearchController,
	}
	rbacService := service.NewRBACService(unitOfWork, userService)
	adminRBACController := admin.NewAdminRBACController(rbacService)
	adminPetSitterController := admin.NewAdminPetSitterController(petSitterService)
	adminControllers := &AdminControllers{
		AdminRBACController:      adminRBACController,
		AdminPetSitterController: adminPetSitterController,
	}
	userPetController := user.NewUserPetController(petService)
	walletService := service.NewWalletService(unitOfWork, petSitterService)
	requestServiceDeps := service.RequestServiceDeps{
		UserService:      userService,
		AddressService:   addressService,
		PetService:       petService,
		PetSitterService: petSitterService,
		WalletService:    walletService,
		UnitOfWork:       unitOfWork,
		EmailService:     emailService,
	}
	requestService := service.NewRequestService(requestServiceDeps)
	userRequestController := user.NewUserRequestController(requestService)
	commentService := service.NewCommentService(unitOfWork, userService, requestService)
	userCommentController := user.NewUserCommentController(commentService)
	userProfileController := user.NewUserProfileController(userService)
	userWalletController := user.NewUserWalletController(walletService)
	userChatController := user.NewUserChatController(chatService, hub)
	userControllers := &UserControllers{
		UserPetController:     userPetController,
		UserRequestController: userRequestController,
		UserChatController:    userChatController,
		UserCommentController: userCommentController,
		UserProfileController: userProfileController,
		UserWalletController:  userWalletController,
	}
	petSitterRegisterController := petsitter.NewPetSitterRegisterController(petSitterService)
	petSitterRequestController := petsitter.NewPetSitterRequestController(requestService)
	petSitterSkillsController := petsitter.NewPetSitterSkillsController(petSitterService)
	petSitterCalendarController := petsitter.NewPetSitterCalendarController(petSitterService)
	petSitterWalletController := petsitter.NewPetSitterWalletController(walletService)
	petSitterChatController := petsitter.NewPetSitterChatController(chatService, hub)
	petSitterControllers := &PetSitterControllers{
		PetSitterRegisterController: petSitterRegisterController,
		PetSitterRequestController:  petSitterRequestController,
		PetSitterSkillsController:   petSitterSkillsController,
		PetSitterCalendarController: petSitterCalendarController,
		PetSitterWalletController:   petSitterWalletController,
		PetSitterChatController:     petSitterChatController,
	}
	controllers := &Controllers{
		GeneralControllers:   generalControllers,
		AdminControllers:     adminControllers,
		UserControllers:      userControllers,
		PetSitterControllers: petSitterControllers,
	}
	localizationMiddleware := middleware.NewLocalizationMiddleware()
	recoveryMiddleware := middleware.NewRecoveryMiddleware()
	authMiddleware := middleware.NewAuthMiddleware(jwtService)
	rbacMiddleware := middleware.NewRBACMiddleware(unitOfWork)
	corsMiddleware := middleware.NewCORSMiddleware()
	middlewares := &Middlewares{
		LocalizationMiddleware: localizationMiddleware,
		RecoveryMiddleware:     recoveryMiddleware,
		AuthMiddleware:         authMiddleware,
		RBACMiddleware:         rbacMiddleware,
		CORSMiddleware:         corsMiddleware,
	}
	databaseSeeder := seeder.NewDatabaseSeeder(db)
	wireSeeder := &Seeder{
		DatabaseSeeder: databaseSeeder,
	}
	wireStorage := &Storage{
		S3Storage: s3Storage,
	}
	application := NewApplication(controllers, middlewares, wireSeeder, wireStorage)
	return application, nil
}

// wire.go:

var StorageProviderSet = wire.NewSet(storage.NewS3Storage, wire.Bind(new(domainstorage.Storage), new(*storage.S3Storage)), wire.Struct(new(Storage), "*"))

var RepositoryProviderSet = wire.NewSet(persistence.NewRepositoryFactory, persistence.NewUnitOfWork, persistence.NewPostgresDatabase, persistence.NewRedisDatabase, redis.NewUserCacheRepository, wire.Bind(new(persistence.Cache), new(*persistence.RedisDatabase)), wire.Bind(new(domainredis.UserCacheRepository), new(*redis.UserCacheRepository)), wire.Bind(new(ports.RepositoryFactory), new(*persistence.RepositoryFactory)), wire.Bind(new(ports.UnitOfWork), new(*persistence.UnitOfWork)))

var ServiceProviderSet = wire.NewSet(wire.Struct(new(service.RequestServiceDeps), "*"), service.NewUserService, jwt.NewJWTService, jwt.NewJWTKeyManager, mail.NewEmailService, service.NewRBACService, service.NewPetService, service.NewRequestService, service.NewAddressService, service.NewPetSitterService, service.NewCommentService, service.NewChatService, service.NewWalletService, wire.Bind(new(jwt.JWTService), new(*jwt.JWTService)), wire.Bind(new(jwt.JWTKeyManager), new(*jwt.JWTKeyManager)), wire.Bind(new(usecase.RBACService), new(*service.RBACService)), wire.Bind(new(usecase.UserService), new(*service.UserService)), wire.Bind(new(usecase.PetService), new(*service.PetService)), wire.Bind(new(usecase.RequestService), new(*service.RequestService)), wire.Bind(new(usecase.AddressService), new(*service.AddressService)), wire.Bind(new(usecase.PetSitterService), new(*service.PetSitterService)), wire.Bind(new(usecase.CommentService), new(*service.CommentService)), wire.Bind(new(usecase.ChatService), new(*service.ChatService)), wire.Bind(new(usecase.WalletService), new(*service.WalletService)), wire.Bind(new(domainmail.Mail), new(*mail.EmailService)))

var GeneralControllersProviderSet = wire.NewSet(general.NewGeneralUserController, general.NewGeneralPetController, general.NewGeneralProvinceController, general.NewGeneralSearchController, wire.Struct(new(GeneralControllers), "*"))

var AdminControllersProviderSet = wire.NewSet(admin.NewAdminRBACController, admin.NewAdminPetSitterController, wire.Struct(new(AdminControllers), "*"))

var UserControllersProviderSet = wire.NewSet(user.NewUserPetController, user.NewUserRequestController, user.NewUserCommentController,user.NewUserChatController, user.NewUserProfileController, user.NewUserWalletController, wire.Struct(new(UserControllers), "*"))

var PetSitterControllersProviderSet = wire.NewSet(petsitter.NewPetSitterRegisterController, petsitter.NewPetSitterRequestController, petsitter.NewPetSitterSkillsController, petsitter.NewPetSitterCalendarController, petsitter.NewPetSitterWalletController, petsitter.NewPetSitterChatController, wire.Struct(new(PetSitterControllers), "*"))

var ControllersProviderSet = wire.NewSet(wire.Struct(new(Controllers), "*"))

var MiddlewaresProviderSet = wire.NewSet(middleware.NewLocalizationMiddleware, middleware.NewRecoveryMiddleware, middleware.NewRBACMiddleware, middleware.NewAuthMiddleware, middleware.NewCORSMiddleware, middleware.NewWebsocketMiddleware, wire.Struct(new(Middlewares), "*"))

var SeederProviderSet = wire.NewSet(seeder.NewDatabaseSeeder, wire.Struct(new(Seeder), "*"))


var ProviderSet = wire.NewSet(
	MiddlewaresProviderSet,
	ControllersProviderSet,
	GeneralControllersProviderSet,
	AdminControllersProviderSet,
	UserControllersProviderSet,
	PetSitterControllersProviderSet,
	ServiceProviderSet,
	RepositoryProviderSet,
	SeederProviderSet,
	StorageProviderSet,
)

type GeneralControllers struct {
	GeneralUserController     *general.GeneralUserController
	GeneralPetController      *general.GeneralPetController
	GeneralProvinceController *general.GeneralProvinceController
	GeneralSearchController   *general.GeneralSearchController
}

type AdminControllers struct {
	AdminRBACController      *admin.AdminRBACController
	AdminPetSitterController *admin.AdminPetSitterController
}

type UserControllers struct {
	UserPetController     *user.UserPetController
	UserRequestController *user.UserRequestController
	UserCommentController *user.UserCommentController
	UserChatController    *user.UserChatController
	UserProfileController *user.UserProfileController
	UserWalletController  *user.UserWalletController
}

type PetSitterControllers struct {
	PetSitterRegisterController *petsitter.PetSitterRegisterController
	PetSitterRequestController  *petsitter.PetSitterRequestController
	PetSitterChatController     *petsitter.PetSitterChatController
	PetSitterSkillsController   *petsitter.PetSitterSkillsController
	PetSitterCalendarController *petsitter.PetSitterCalendarController
	PetSitterWalletController   *petsitter.PetSitterWalletController
}

type Controllers struct {
	GeneralControllers   *GeneralControllers
	AdminControllers     *AdminControllers
	UserControllers      *UserControllers
	PetSitterControllers *PetSitterControllers
}

type Middlewares struct {
	LocalizationMiddleware *middleware.LocalizationMiddleware
	RecoveryMiddleware     *middleware.RecoveryMiddleware
	AuthMiddleware         *middleware.AuthMiddleware
	RBACMiddleware         *middleware.RBACMiddleware
	CORSMiddleware         *middleware.CORSMiddleware
	WebsocketMiddleware    *middleware.WebsocketMiddleware
}

type Seeder struct {
	DatabaseSeeder *seeder.DatabaseSeeder
}

type Storage struct {
	S3Storage *storage.S3Storage
}

type Application struct {
	Controllers *Controllers
	Middlewares *Middlewares
	Seeder      *Seeder
	Storage     *Storage
}

func NewApplication(controllers *Controllers, middlewares *Middlewares, seeder2 *Seeder, storage2 *Storage) *Application {
	return &Application{
		Controllers: controllers,
		Middlewares: middlewares,
		Seeder:      seeder2,
		Storage:     storage2,
	}
}
